const v2 = this.TypeError;
let v3;
try { v3 = v2(); } catch (e) {}
with ("valueOf") {
    --v3;
}
